# Generated by Django 3.2.16 on 2023-11-04 18:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('competition_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('competition', models.CharField(max_length=150)),
                ('time', models.CharField(default=None, max_length=19)),
                ('room_time', models.IntegerField(default=None, null=True)),
                ('level', models.IntegerField(default=0)),
                ('left_level', models.IntegerField(default=0)),
            ],
        ),
    ]
