# Generated by Django 3.2.16 on 2023-11-04 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('participant_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.IntegerField(default=1)),
                ('Score', models.DecimalField(decimal_places=20, default=0.0, max_digits=100)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.competition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('match_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_date_time', models.DateTimeField(auto_now=True, null=True)),
                ('level', models.IntegerField(default=0)),
                ('competition', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='competition.competition')),
                ('opponent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to='user.participant')),
                ('player', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='user.participant')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='user.participant')),
            ],
        ),
    ]
